version: '3.8'
services: 
  database: 
    image: postgres:13
    container_name: database_bst
    env_file: 
      - .env
    ports: 
      - "5432:5432"
    volumes:  
      - database_data:/var/lib/postgresql/data
    networks: 
      - boostrap_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bst
    env_file: 
      - .env
    ports:
      - "5050:80"
    volumes:
      - .:/app
    depends_on: 
      database:   
        condition: service_healthy
    networks: 
      - boostrap_network

  web: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_bst
    depends_on: 
      database:   
        condition: service_healthy
    ports:
      - "4000:4000"
    networks: 
      - boostrap_network
    
  

volumes: 
  database_data:
  pgadmin_data:

networks: 
  boostrap_network:
